# Generated by Django 4.1.6 on 2023-03-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jagruti',
            new_name='Seller',
        ),
    ]
