# Generated by Django 4.1.6 on 2023-03-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_jagruti_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='roll_no',
            new_name='roll_no',
        ),
    ]
