# Generated by Django 4.1.6 on 2023-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_roll_no_seller_rollp_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='gst_no',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='sad.jpg', upload_to='profile_pics'),
        ),
    ]
