# Generated by Django 4.1.6 on 2023-03-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_remove_seller_roll_no_seller_address_seller_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=255)),
                ('price', models.FloatField(default=10.5)),
                ('product_stock', models.IntegerField(default=0)),
                ('pic', models.FileField(default='sad.jpg', upload_to='product_pics')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
