# Generated by Django 4.1.6 on 2023-03-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pasword',
            new_name='password',
        ),
    ]
