# Generated by Django 4.1.6 on 2023-03-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
